language: node_js
node_js:
  - node
cache: npm
deploy:
  provider: heroku
  api_key:
    secure: ga+4yGNd+BSkEOlmMmP/k6D/z6xnOl5CFShSe6wygn81oS3f/Q98nLAGX+LwIGsFjHLKeXsFyk2WJMXyBWr39hB04tDCFNgfqvznDascFBwh+t3yyytbb94tvSZ2yB1IZbXitdd3SxCenhop+Jy41M1m2xQmUJgKI5LVz4Wsi7xadfGuadLQB0S9JBXCA4GOOkhKYFZRz6EaNmw2ZbnQqapB445LWwC9rwUGe/M7635BiAa4238gb6BSpsUXI8ZTPZchqy9INazE48grxEyVIupcdjzYe4ipBzrgyHgZId3kvXsCy2USznX59mO0UaOZ7NBQ+Bb1jzEGHm2KWuf26MxGJA+TTvXE+BfRBG/PNWvbaM7/JiuQ0XTX0zls2sb6HrccAVc9302QM952SrfxMY4udPpmgWGSw/vyFWKKkI1xsgYUilm1W9YXN1Xm2hrA539BKmFnFsoM9ylIRYkAo9e8NGjV+gHCksM/WPGVslDmZhNZczpz5nGmywsWtds66uSxqFZLd9LPhFtxAidDGILZFXY0k29hLzRAMLL4+AqzIu/M6d4zsb5xeYpatXE3XeSuJP3gLViQG5FV+iWpvzTm7TnwPIC710b5paFgSIdnL3w/cJgN4lY0V5pAwEzlP/dnYN+Fv0/xIJ4HLRFCiGMdM9oiUKbQ0rW54AY1lC8=
  app: pressure-relief-design-je
